language: csharp
solution: "./Test-Project/ARDrone2-Project.sln"
install:
  - nuget restore "./Test-Project/ARDrone2-Project.sln"
  - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Debug ./Test-Project/ARDrone2-Project.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./Test-Project/WARD-UnitTesting/bin/Debug/WARD-UnitTesting.dll